name: Push nuget package to github packages
on:
  push
jobs:
  nuget-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set VERSION variable from workflow
      run: echo "VERSION=${GITHUB_RUN_ID}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
    - name: Pack
      run: dotnet pack --no-build --output .
    - name: Push
      run: dotnet nuget push /home/runner/work/gitops-with-azure/gitops-with-azure/gitops-with-azure.${VERSION}.nupkg --source "https://nuget.pkg.github.com/cwalshtandem/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
